### ISSUE TITLE
How to render spaces

### ISSUE THREAD

**Issue by KinsonDigital** [ryancheung/FreeTypeSharp#10]
Hello!! 

I hope that this is the right place to ask for help.  There is no discussion section to use so this is the only thing I can think of.  😊

My issue is with rendering spaces between words that are proportional.

I have basically setup a test program using the tutorial from the [FreeType2](https://www.freetype.org/) website.
I used a combination of stuff from the [Step 1](https://www.freetype.org/freetype2/docs/tutorial/step1.html#basic-code) and [Step 2 - Section 4](https://tools.ietf.org/doc/libfreetype6/tutorial/step2.html) pages.

Now I know that spaces do not have faces/glyphs to be rendered, so I figured that I would somehow proportionally increase the X position for the next character and just skip rendering for **space** since there is nothing to render.  I, of course, do get some space between the words but that space is hardcoded and this will not work for other font sizes.

Here are some samples of the space between the words on 2 different font sizes.  Again, I know why it is doing this, I just don't know how I would properly render spaces. 

---

**Font Size 12:**
![image](https://user-images.githubusercontent.com/4921022/112828092-40e46400-905d-11eb-8570-a7fc3941e5f6.png)

**Font Size 54:**
![image](https://user-images.githubusercontent.com/4921022/112828117-4cd02600-905d-11eb-95d1-51146614a514.png)

Thanks for any help you can provide!!

**Comment by ryancheung** [comment]
The wdith of space character is actually defined in glyph metric. You should use the advance of glyph instead of hard-coded space width.
```
FT.FT_Load_Char(_FaceRec, codePoint, loadFlags);
var spaceWidth = (int)_FaceRec->glyph->metrics.horiAdvance >> 6;
```
https://github.com/ryancheung/FreeTypeSharp/blob/master/FreeTypeSharp.Shared/FreeTypeFaceFacade.cs#L102

**Comment by KinsonDigital** [comment]
Awesome.  Thanks a lot for your help.  I will give that a shot and close the comment if I get this working.  😊

**Comment by KinsonDigital** [comment]
That worked perfectly!! Thanks!!

**Comment by ryancheung** [comment]
np

**Comment by KinsonDigital** [comment]
Great library by the way!!  It is helping me greatly!!
