### ISSUE TITLE
Upgrade to FreeType 2.11.0 to support signed distance fields

### ISSUE THREAD

**Issue by Abrynos** [ryancheung/FreeTypeSharp#14]
As the title says: I'd like this library use FreeType version 2.11.0 to support the rendering module for signed distance fields.

**Comment by ryancheung** [comment]
The latest nuget pacakge `2.0.0.3-ci` should include this fix now. I have no idea of rendering **sdf** font with freetype2. Let me know if there're still API missing for sdf font rendering.
