### ISSUE TITLE
Upgrade FreeType to 2.11.1 (or higher) to fix crash

### ISSUE THREAD

**Issue by trolleyman** [ryancheung/FreeTypeSharp#20]
@ryancheung Hi - thanks for this libary, it's been very good so far. I have encountered a crash with the latest version - while loading a glyph in `FreeTypeSharp`:

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at FreeTypeSharp.Native.FT.FT_Load_Glyph(IntPtr, UInt32, Int32)
```

I believe this is caused by this issue: https://gitlab.freedesktop.org/freetype/freetype/-/issues/1075 - fixed in https://gitlab.freedesktop.org/freetype/freetype/-/commit/5bcaf51b611ce579c89c2bb423984ec89fdaadd7.

I'm not sure but this was probably introduced by updating to 2.11.0 in https://github.com/ryancheung/FreeTypeSharp/pull/16. This can be fixed by updating to 2.11.1 or higher (max 2.12.1).

**Comment by ryancheung** [comment]
freetype has been updated to v2.13.2
