### ISSUE TITLE
Support for Java 8

### ISSUE THREAD

**Issue by robertjb20** [ryancheung/FreeTypeSharp#23]
This message is from the Java website regarding Java version 11:

"WARNING: These older versions of the JRE and JDK are provided to help developers debug issues in older systems. They are not updated with the latest security patches and are not recommended for use in production."

Please upgrade to the latest version of Java:

Recommended Version 8 Update 381
Release date: July 18, 2023.

Thank you.

**Comment by ryancheung** [comment]
This is not a lib for java, it's for .net.
