### ISSUE TITLE
tried installing with nuget vscode extenstion. 

### ISSUE THREAD

**Issue by nasrra** [ryancheung/FreeTypeSharp#27]
error NU1202: Package F
reeTypeSharp.UWP 3.0.0 is not compatible with net8.0 (.NETCoreApp,Version=v8. ng N      
0). Package FreeTypeSharp.UWP 3.0.0 supports: uap10.0.16299 (UAP,Version=v10. y Sh      
0.16299) 

csproj:
    <PackageReference Include="FreeTypeSharp" Version="3.0.0"/>
    <PackageReference Include="FreeTypeSharp.UWP" Version="3.0.0"/>
    <PackageReference Include="FreeTypeSharp.Core" Version="0.8.0"/>

**Comment by nasrra** [comment]
PackageReference Include="FreeTypeSharp" Version="3.0.0"
    PackageReference Include="FreeTypeSharp.UWP" Version="3.0.0"
    PackageReference Include="FreeTypeSharp.Core" Version="0.8.0"

**Comment by ryancheung** [comment]
Just use `PackageReference Include="FreeTypeSharp" Version="3.0.0"` and avoid the others. `FreeTypeSharp.UWP` is for Windows UWP only, `FreeTypeSharp.Core` is deprecated.

**Comment by nasrra** [comment]
yeah sorry, figured that out a moment ago, had a bit of a brain fart :) thank you!

**Comment by ryancheung** [comment]
np :)
